<?php

// $Id$

/**
*
*
*/

/**
Implements Hook_menue
*/

function mymodule_menu(){
	
	$items['myfirst-module'] = array (
	'title' => 'My first module',
	'description' => 'This is my first module with text',
	'page callback' => 'mymodule_page',
	'access arguments' => array('access content'),


	);
	return $items;

}

function mymodule_page(){
	$output = '';

	$output .= '<p>Hey, this is my first module, it works, great!</p>';

	// adding this here does nothing. 
	//drupal_add_js('jQuery(document).ready(function ($) { alert("Hello all!!"); });', 'inline');

	return $output;


}


