<?php

// $Id$

/**
*
*
*/

//

function mymodule_menu(){
	
	$items['myfirst-module'] = array (
	'title' => 'My first module',
	'description' => 'This is my first module with text',
	'page callback' => 'mymodule_page',
	'access arguments' => array('access content'),


	);
	return $items;

}

function mymodule_page(){
	$output = '';

	$output .= '<p>Hey, this is my first module, it works, great!</p>';

	return $output;

}


// adds css and JS files after all the drupal modules have been loaded.

function mymodule_init() {
    drupal_add_css(drupal_get_path('module', 'mymodule') .'/autocomplete.css');
    drupal_add_css(drupal_get_path('module', 'mymodule') .'jquery-ui-1.12.0/jquery-ui.css');

    drupal_add_js(drupal_get_path('module', 'mymodule') .'/jquery.ui.autocomplete.html.js');
        drupal_add_js(drupal_get_path('module', 'mymodule') .'/autocomplete.js');
    $settings = variable.get('mymodule', unserialize(MYMODULE_DEFAULT)
    );
    drupal_add_js(array('mymodule' => $settings), 'setting');
    }




