<?php

/**
 * @file
 * A module for adding js of a dropdown menu for the user to select the data they want to display in the BioJs component.
 */

/**
this implements Hook init 
this loads all non-cached pages
*/
function dataform_init() {
  if (current_path() == 'node/1') {
    drupal_add_js('misc/dataform_menu.js');
    drupal_add_js('jQuery(document).ready(function () { alert("Hello from the dataform.module!"); });', 'inline');
  }
}
//  //since this file should only be loaded on the front page, it cannot be declared in the info file.
 /* if (drupal_is_front_page()) {
    drupal_add_css(drupal_get_path('module', 'dataform_menu')) . '/dataform.css');
  }*/
//}


/**
Implements Hook_menu
hook enables modules to register paths in order to define how URL requests are handled.
or they can register a link to be placed in a menue (usually the Navigation menu).
it's results are cached in the database.  
its implementation returns an associative array whose keys define paths and whole values 
*/

function dataform_menu() {

  $items['my/example'] = array(
  'title' => 'my dataform module page test',
  'description' => 'my test',
  'access callback' => true, // available to all
  'page callback' => 'my_example_page', //definition of the path. // the function to call to display a web page when the user visits the path. If omitted, the parent menu item's callback be used instead.
  //'delivery callback' => 'drupal_json_output'
  'access arguments' => array('access content'),
  'type' => MENU_NORMAL_ITEM,

  );
  return $items; 
}

/**
 * Implements hook_theme
 *
 */
function dataform_menu_theme($existing, $type, $theme, $path) {
  return array(
    'the_html_page' => array(
    'template' => 'the-html-page', /* create file with this name + .tpl.php */
  ),
);
}

// vip: http://drupal.stackexchange.com/questions/101659/pass-php-page-to-page-callback-with-hook-menu

// function dataform_fancystuff_object() {
//     return array('test'=>true,'dummy'=>array(0,1));
// }


function my_example_page(){
  return theme('the_html_page');
}



/** 
* Implementation of hook_init()
* Add CSS, Javascript and settings to the page
*/

// function dataform_menu_init() {
//   drupal_add_js(drupal_get_path('module', 'dataform_menu') .'/dataform_menu.js');
//   $settings = variable_get('dataform_menu_effects', unserialize(DATAFORM_MENU_DEFAULT));
//   drupal_add_js(array('dataformMenu' => $settings), 'setting');
// }
/*
def autocomplete
    #puts "In autocomplete!"
    gene_set_id = session[:gene_set_id] 
    @genes = Gene.order(:name).where("name LIKE ? and gene_set_id = ?", "%#{params[:term]}%", gene_set_id).limit(20)

    respond_to do |format|
      format.html
      format.json { 
        render json: @genes.map(&:name)
      }
    end
  end*/
?>

